### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by Jakobimatagi** [code-arman/Cleanify#20]
<img width="371" alt="Screenshot 2024-03-22 at 8 41 11 AM" src="https://github.com/code-arman/Cleanify/assets/72160375/539972c7-c761-49c2-948e-f208faea499a">

When I clicked on it nothing happened but I clicked the `View on Github` to get here and that worked!

**Comment by code-arman** [comment]
Could you make a PR for this if you get a chance? I will approve it
